services:
  postgres:
    image: postgres:16-alpine
    container_name: next15_ecommerce
    ports:
      - "5452:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next15_ecommerce
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
